#!/usr/bin/env ruby
# frozen_string_literal: true

require 'erb'
require 'octokit'

Octokit.configure do |c|
  c.auto_paginate = true
end

Octokit::Client.new(
  access_token: ENV['GITHUB_TOKEN']
).tap do |client|
  @repos = client.org_repos('gopad').map(&:name).sort.select do |row|
    row.start_with? 'gopad-'
  end.append('homebrew-gopad')

  File.write(
    File.expand_path(
      '../STATUS.md',
      __dir__
    ),
    ERB.new(
      File.read(
        File.expand_path(
          '../templates/status.erb',
          __dir__
        )
      ), trim_mode: '-'
    ).result
  )
end
